const {
  REACT_APP_BACKEND_HOST,
  REACT_APP_IMAGE_HOST,
  REACT_APP_SADMIN,
  REACT_APP_VERSION,
  REACT_APP_DEFAULT_LANGUAGE,
  REACT_APP_SHARE_HOST,
  REACT_APP_VIDEOS_PER_PAGE,
  REACT_APP_MAX_RELATED_VIDEOS,
  REACT_APP_ITEM_PER_PAGE,
  REACT_APP_PLACE_HOST,
  REACT_APP_GOOGLE_MAP_API_KEY
} = process.env;

export default {
  BACKEND_HOST: REACT_APP_BACKEND_HOST,
  IMAGE_HOST: REACT_APP_IMAGE_HOST,
  SADMIN: REACT_APP_SADMIN,
  VERSION: REACT_APP_VERSION,
  DEFAULT_LANGUAGE: REACT_APP_DEFAULT_LANGUAGE,
  SHARE_HOST: REACT_APP_SHARE_HOST,
  VIDEOS_PER_PAGE: REACT_APP_VIDEOS_PER_PAGE,
  MAX_RELATED_VIDEOS: REACT_APP_MAX_RELATED_VIDEOS,
  ITEM_PER_PAGE: REACT_APP_ITEM_PER_PAGE,
  PLACE_HOST: REACT_APP_PLACE_HOST,
  GOOGLE_MAP_API_KEY: REACT_APP_GOOGLE_MAP_API_KEY
};
